apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-agent
  labels:
    name: prometheus-agent
  namespace: rciots-agent
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1m
      evaluation_interval: 1m
    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https
    remote_write:
    - url: 'http://localhost:8080/metrics'
      queue_config:
        max_samples_per_send: 2000
      metadata_config:
        send_interval: 3m
        max_samples_per_send: 2000