apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: rciots-agent
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [OUTPUT]
        Name          http
        Match         *
        Host          rciots-agent
        Port          8080
        URI           /logs
        Format        json_lines
        Header        Content-Type application/x-www-form-urlencoded