apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: rciots-agent
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        Health_Check On

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        multiline.parser docker, cri
        Tag               kube.*
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name    grep
        Match   *
        Exclude $kubernetes['labels']['app'] rciots-agent

    [OUTPUT]
        Name          http
        Match         *
        Host          localhost
        Port          8080
        URI           /logs
        Format        json_lines
        Header        Content-Type application/x-www-form-urlencoded