apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: fluent-bit-scc
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: RunAsAny